/* eslint-disable import/prefer-default-export */

// application
import { IBrand } from '~/interfaces/brand';

export const brands: IBrand[] = [
    {
        slug: 'dayco',
        name: 'Dayco',
        country: 'US',
        image: '/images/Manufacturers/1741082163_o349p3_dayco.svg',
    },
    {
        slug: 'castrol',
        name: 'Castrol',
        country: 'UK',
        image: '/images/Manufacturers/1741850820_o3d7q0_castrol.svg',
    },
    {
        slug: 'mann-filter',
        name: 'MANN-FILTER',
        country: 'DE',
        image: '/images/Manufacturers/1742901822_o3obmc_mann_filter.svg',
    },
    {
        slug: 'ngk',
        name: 'NGK',
        country: 'JP',
        image: '/images/Manufacturers/1742907550_o3ocsa_ngk.svg',
    },
    {
        slug: 'contitech',
        name: 'ContiTech',
        country: 'DE',
        image: '/images/Manufacturers/1742977635_o3p8qf_contitech.png',
    },
    {
        slug: 'denso',
        name: 'DENSO',
        country: 'JP',
        image: '/images/Manufacturers/1742984980_o3pasa_denso.png',
    },
    {
        slug: 'metzger',
        name: 'METZGER',
        country: 'DE',
        image: '/images/Manufacturers/1742987808_o3pbeh_metzger.png',
    },
    {
        slug: 'snr',
        name: 'SNR',
        country: 'FR',
        image: '/images/Manufacturers/1742989516_o3pbfe_snr.png',
    },
    {
        slug: 'nissens',
        name: 'NISSENS',
        country: 'DK',
        image: '/images/Manufacturers/1742990550_o3pc2_nissens.svg',
    },
    {
        slug: 'nrf',
        name: 'NRF',
        country: 'NL',
        image: '/images/Manufacturers/1743001331_o3pf2b_nrf.png',
    },
    {
        slug: 'meyle',
        name: 'MEYLE',
        country: 'DE',
        image: '/images/Manufacturers/1743002419_o3pfji_meyle.svg',
    },
    {
        slug: 'fag',
        name: 'FAG',
        country: 'DE',
        image: '/images/Manufacturers/1743070979_o3qals_fag.svg',
    },
    {
        slug: 'trw',
        name: 'TRW',
        country: 'US',
        image: '/images/Manufacturers/1743071210_o3qapj_trw.png',
    },
    {
        slug: 'motive',
        name: 'MOTIVE',
        country: 'DE',
        image: '/images/Manufacturers/1743071346_o3qas6_motive.png',
    },
    {
        slug: 'jp-group',
        name: 'JP GROUP',
        country: 'DK',
        image: '/images/Manufacturers/1743071396_o3qasp_jp_group.png',
    },
    {
        slug: 'alte-automotive',
        name: 'ALTE Automotive',
        country: 'DE',
        image: '/images/Manufacturers/1743071894_o3qa8e_alte_automotive.png',
    },
    {
        slug: 'krown',
        name: 'KROWN',
        country: 'CA',
        image: '/images/Manufacturers/1743071929_o3qa8i_krown.png',
    },
    {
        slug: 'mahle-original',
        name: 'MAHLE Original',
        country: 'DE',
        image: '/images/Manufacturers/1743072107_o3qabg_mahle_original.svg',
    },
    {
        slug: 'kamoka',
        name: 'KAMOKA',
        country: 'PL',
        image: '/images/Manufacturers/1743675578_o43ai8_kamoka.png',
    },
    {
        slug: 'swag',
        name: 'SWAG',
        country: 'DE',
        image: '/images/Manufacturers/1743686220_o43dg0_swag.svg',
    },
    {
        slug: 'tyc',
        name: 'TYC',
        country: 'TW',
        image: '/images/Manufacturers/1743687543_o43d93_tyc.png',
    },
    {
        slug: 'liqui-moly',
        name: 'LIQUI MOLY',
        country: 'DE',
        image: '/images/Manufacturers/1743688413_o43dm3_liqui_moly.svg',
    },
    {
        slug: 'gsp',
        name: 'GSP',
        country: 'CN',
        image: '/images/Manufacturers/1744012041_o477gk_gsp.png',
    },
    {
        slug: 'mfilter',
        name: 'MFILTER',
        country: 'FI',
        image: '/images/Manufacturers/1744015625_o478g5_mfilter.png',
    },
    {
        slug: 'mobil',
        name: 'Mobil',
        country: 'US',
        image: '/images/Manufacturers/1744015964_o478le_mobil.svg',
    },
    {
        slug: 'total',
        name: 'Total',
        country: 'FR',
        image: '/images/Manufacturers/1744025481_o47b1k_total.svg',
    },
    {
        slug: 'magneti-marelli',
        name: 'Magneti Marelli',
        country: 'IT',
        image: '/images/Manufacturers/1744039201_o47fj1_magneti_marelli.svg',
    },
    {
        slug: 'sachs',
        name: 'SACHS',
        country: 'DE',
        image: '/images/Manufacturers/1744039334_o47fle_sachs.svg',
    },
    {
        slug: 'lesjofors',
        name: 'Lesjöfors',
        country: 'SE',
        image: '/images/Manufacturers/1744382770_o4beea_lesjofors.svg',
    },
    {
        slug: 'monroe',
        name: 'Monroe',
        country: 'US',
        image: '/images/Manufacturers/1744616641_o4e7e1_monroe.svg',
    },
    {
        slug: 'febi-bilstein',
        name: 'febi bilstein',
        country: 'DE',
        image: '/images/Manufacturers/1748943905_o639f5_febi_bilstein.png',
    },
    {
        slug: 'luk',
        name: 'LuK',
        country: 'DE',
        image: '/images/Manufacturers/1748944417_o639m7_luk.svg',
    },
    {
        slug: 'skf',
        name: 'SKF',
        country: 'SE',
        image: '/images/Manufacturers/1748944706_o639rp_skf.svg',
    },
    {
        slug: 'gates',
        name: 'Gates',
        country: 'US',
        image: '/images/Manufacturers/1748944772_o639s2_gates.svg',
    },
    {
        slug: 'maxgear',
        name: 'MAXGEAR',
        country: 'DE',
        image: '/images/Manufacturers/1748944826_o63a0p_maxgear.png',
    },
    {
        slug: 'delphi',
        name: 'Delphi',
        country: 'US',
        image: '/images/Manufacturers/1748945060_o63a4j_delphi.svg',
    },
    {
        slug: 'valeo',
        name: 'Valeo',
        country: 'FR',
        image: '/images/Manufacturers/1749112285_o6581o_valeo.svg',
    },
    {
        slug: 'brembo',
        name: 'Brembo',
        country: 'IT',
        image: '/images/Manufacturers/1749219043_o66ead_brembo.svg',
    },
    {
        slug: 'lemforder',
        name: 'Lemförder',
        country: 'DE',
        image: '/images/Manufacturers/1749472440_o69c40_lemforder.svg',
    },
    {
        slug: 'febest',
        name: 'FEBEST',
        country: 'DE',
        image: '/images/Manufacturers/1750066940_o6e9cj_febest.svg',
    },
    {
        slug: 'ina',
        name: 'INA',
        country: 'DE',
        image: '/images/Manufacturers/1754478559_1749198070_o668ka_ina.png',
    },
    {
        slug: 'blue-print',
        name: 'Blue Print',
        country: 'UK',
        image: '/images/Manufacturers/1754478595_1745828136_o4r8f6_blue_print.png',
    },
    {
        slug: 'bosch',
        name: 'Bosch',
        country: 'DE',
        image: '/images/Manufacturers/1754479164_o86bin_bosch.svg',
    },
    {
        slug: 'hella',
        name: 'HELLA',
        country: 'DE',
        image: '/images/Manufacturers/1754479647_1742564945_o3kdi5_hella.png',
    },
    {
        slug: 'fast',
        name: 'FAST',
        country: 'IT',
        image: '/images/Manufacturers/1754490614_o86ee_fast.svg',
    },
    {
        slug: 'esen-skv',
        name: 'ESEN SKV',
        country: 'DE',
        image: '/images/Manufacturers/1754509132_1748944873_o63a1d_esen_skv.png',
    },
    {
        slug: 'a-b-s',
        name: 'A.B.S.',
        country: 'NL',
        image: '/images/Manufacturers/1754725090_o8978a_a_b_s.png',
    },
];
